### PR TITLE
Update sips.md

### PR DESCRIPTION
**Pull request by bogachevanton**
## Description

Update SIPs list: added SIP-013

### CODE REVIEW

**Review by obycode — APPROVED** [review]
LGTM!

**Comment by wileyj** [comment]
@bogachevanton would you mind rebasing and note the file location has changed to `.docs/stacks-academy/sips.md`

**Comment by wileyj** [comment]
> @bogachevanton would you mind rebasing and note the file location has changed to `.docs/stacks-academy/sips.md`

ping @bogachevanton

**Comment by bogachevanton** [comment]
> > @bogachevanton would you mind rebasing and note the file location has changed to `.docs/stacks-academy/sips.md`
> 
> ping @bogachevanton 

Ok, got it

**Pull request closed without merging**
