### PR TITLE
fix: correct github links and references

### PR DESCRIPTION
**Pull request by esopian**
## Description
While browsing the published documentation I noticed that the github links sent me to a "Moved" org.  Correcting the links and references do avoid user confusion.

## Checklist

- [X] [Conventional commits were used](https://www.conventionalcommits.org/en/v1.0.0/)
- [X] New links to files and images were verified
- [X] For fixes/refactors: all existing references were identified and replaced
- [X] [Style guide](https://developers.google.com/style) was reviewed and applied
- [X] Clear code samples were provided
- [x] People were tagged for review

### CODE REVIEW

**Comment by criadoperez** [comment]
Thank for for your contribution @esopian !
You need to first sign the CLA before we can accept your contribution.

**Comment by esopian** [comment]
> Thank for for your contribution @esopian ! You need to first sign the CLA before we can accept your contribution.

Done and Done

**Comment by esopian** [comment]
> Please run prettier on this file so it modifies the rest of the table and passes the _prettier_ check. `prettier --write gaia.md`

Sure. 
Would you want me to add automated prettier runs with husky so all contributions are prettier-ed before PR?

**Comment by esopian** [comment]
oh wait, it's already there.  huh.  don't know how mine skipped it.   on it.

**Comment by esopian** [comment]
@criadoperez Prettier formatting done

**Pull request merged**
