### PR TITLE
Fix example for account creation

### PR DESCRIPTION
**Pull request by empeje**
## Description

Describe the changes that were made in this pull request. When possible start with the motivations behind the change. Be sure to also include the following information:

1. Motivation for change?

I try the original code and it doesn't work.

2. What was changed?

Add required info to import

3. Link to relevant issues?

## Checklist

- [ ] [Conventional commits were used](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] New links to files and images were verified
- [ ] For fixes/refactors: all existing references were identified and replaced
- [ ] [Style guide](https://developers.google.com/style) was reviewed and applied
- [ ] Clear code samples were provided
- [ ] People were tagged for review

### CODE REVIEW

**Comment by empeje** [comment]
Could you please review @jhammond2012

**Comment by jhammond2012** [comment]
@empeje be sure to sign the CLA

**Comment by empeje** [comment]
Done @jhammond2012

**Review by jhammond2012 — APPROVED** [review]

**Review by jhammond2012 — APPROVED** [review]

**Comment by empeje** [comment]
Sure @criadoperez, I'll update.

**Comment by criadoperez** [comment]
Thank you!

**Comment by criadoperez** [comment]
@empeje, because there has been a conflict open for some time, I'm closing the issue. Please re-summit the fix in a new PR, as that might be easier.

**Pull request closed without merging**
